### ISSUE TITLE
I am a copyright owner of the Build.MD you ripped from the website

### ISSUE THREAD

**Issue by anoraktrend** [fn2006/PolyMC#2]
The Site is not Creative Commons, it's copyright is given to those that have contributed to it. As one such contributer, I politely request you remove it from this repo.

**Comment by anoraktrend** [comment]
(Or remove my contributions at the very least.)

**Comment by LennyMcLennington** [comment]
The site is licensed under AGPL, they have a legal right to distribute that file. However since you attempt to abuse your copyright to deny freedom to people, completely missing the entire point of free software philosophy, it might be best to remove your existing contributions from PolyMC's website and prevent you from contributing to PolyMC in the future in order to avoid any further attempts at abusing your status as a copyright holder. We want contributions from people who try to uphold user freedom, not stifle it. Not that you actually have any legal right to get anything taken down, but just the fact that you seem to not understand the concept of a license and seem to not care about user freedom at all.

**Comment by fn2006** [comment]
I don't mind removing it, should I remove BUILD.md entirely or just replace it's contents with the upstream version that points to the website?
Also while we're on the topic of licensing, are there any other changes you want me to make? (e.g. changing the readme, repo name, etc)

**Comment by anoraktrend** [comment]
Personally, replace it with upstream and point to the website. A small suggestion for adding an L to Poly,  to make it "Polly" would be a good idea.

**Comment by anoraktrend** [comment]
(Polly is a reference to parots, because parots are associated with tropical areas.)

**Comment by fn2006** [comment]
Alright, closing this since I've replaced BUILD.md with upstream.

BTW that PollyMC idea is genius, I had decided was going to rename the repo to GratisMC if you guys wanted it changed but PollyMC is way cooler.
